kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30280  # NodePort assigned to the service
        hostPort: 30280       # Port on EC2 host
        protocol: TCP
